/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bucks (https://sketchfab.com/Its_Bucks)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-house-47f72a00282e450b9d9ef7044a70ad70
Title: Viking House
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const VikingHouse = (...props) =>{
  const { nodes, materials } = useGLTF('/viking_house.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={212.766}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube125_lambert2_0.geometry}
            material={materials.lambert2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube125_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube125_lambert3_0.geometry}
            material={materials.lambert3}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/viking_house.glb')
export default VikingHouse;